"use client"

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { format, parseISO } from "date-fns"
import { CalendarDays, LoaderCircle, Pencil, Search, SlidersHorizontal, Trash2, UsersRound, X } from "lucide-react"
import { usePathname, useRouter, useSearchParams } from "next/navigation"
import { useCallback, useEffect, useMemo, useState, type ReactNode } from "react"
import type { DateRange } from "react-day-picker"
import { toast } from "sonner"

import { PageContainer } from "@/components/admin/page-container"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Calendar } from "@/components/ui/calendar"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Pagination, PaginationContent, PaginationItem, PaginationNext, PaginationPrevious } from "@/components/ui/pagination"
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Separator } from "@/components/ui/separator"
import { Sheet, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet"
import { Skeleton } from "@/components/ui/skeleton"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip"
import { deletePatient, PatientApiError } from "@/features/patients/patient.api"
import { patientListQueryOptions, patientQueryKeys } from "@/features/patients/patient.queries"
import { dashboardQueryKeys } from "@/features/dashboard/dashboard.queries"
import type { GlobalPatient, PatientListParameters } from "@/features/patients/patient.schema"
import { doctorListQueryOptions } from "@/features/doctors/doctor.queries"
import { cn } from "@/lib/utils"
import { PatientFormDialog } from "./patient-form-dialog"

const PAGE_SIZES = [10, 20, 50] as const
const dateFormat = new Intl.DateTimeFormat("en-US", { year: "numeric", month: "short", day: "numeric", timeZone: "UTC" })
const optional = (value: string): string | undefined => value.trim() || undefined
const positive = (value: string | null, fallback: number, allowed?: readonly number[]): number => { const number = Number(value); return Number.isInteger(number) && number > 0 && (allowed === undefined || allowed.includes(number)) ? number : fallback }
const rangeFrom = (start: string, end: string): DateRange | undefined => start ? { from: parseISO(start), ...(end ? { to: parseISO(end) } : {}) } : undefined
const iso = (date: Date | undefined): string => date ? format(date, "yyyy-MM-dd") : ""

interface FilterDraft { doctorId: string; condition: string; limit: number }

function FilterFields({ idPrefix, draft, setDraft, doctors }: { idPrefix: string; draft: FilterDraft; setDraft: (draft: FilterDraft) => void; doctors: readonly { id: string; name: string }[] }) {
  return <div className="space-y-4"><div><Label htmlFor={`${idPrefix}-doctor`}>Doctor</Label><Select value={draft.doctorId || "all"} onValueChange={(value) => setDraft({ ...draft, doctorId: value === "all" ? "" : String(value) })}><SelectTrigger id={`${idPrefix}-doctor`} className="mt-2 w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All doctors</SelectItem>{doctors.map((doctor) => <SelectItem key={doctor.id} value={doctor.id}>{doctor.name}</SelectItem>)}</SelectContent></Select></div><div><Label htmlFor={`${idPrefix}-condition`}>Condition</Label><Input id={`${idPrefix}-condition`} className="mt-2" placeholder="Exact condition" value={draft.condition} onChange={(event) => setDraft({ ...draft, condition: event.target.value })} /></div><div><Label htmlFor={`${idPrefix}-limit`}>Patients per page</Label><Select value={String(draft.limit)} onValueChange={(value) => setDraft({ ...draft, limit: Number(value) })}><SelectTrigger id={`${idPrefix}-limit`} className="mt-2 w-full"><SelectValue /></SelectTrigger><SelectContent>{PAGE_SIZES.map((size) => <SelectItem key={size} value={String(size)}>{size}</SelectItem>)}</SelectContent></Select></div></div>
}

function FilterControls({ active, draft, setDraft, doctors, onOpening, onApply, onReset }: { active: boolean; draft: FilterDraft; setDraft: (draft: FilterDraft) => void; doctors: readonly { id: string; name: string }[]; onOpening: () => void; onApply: () => void; onReset: () => void }) {
  const [popoverOpen, setPopoverOpen] = useState(false)
  const [sheetOpen, setSheetOpen] = useState(false)
  const trigger = <Button type="button" variant={active ? "default" : "outline"} size="icon" aria-label="Patient filters"><SlidersHorizontal aria-hidden="true" /></Button>
  return <><div className="hidden sm:block"><Popover open={popoverOpen} onOpenChange={(open) => { if (open) onOpening(); setPopoverOpen(open) }}><Tooltip><TooltipTrigger render={<PopoverTrigger render={trigger} />}><span className="sr-only">Open filters</span></TooltipTrigger><TooltipContent>Patient filters</TooltipContent></Tooltip><PopoverContent align="end" className="w-80"><FilterFields idPrefix="desktop-global-patient" draft={draft} setDraft={setDraft} doctors={doctors} /><Separator className="my-4" /><div className="flex justify-between"><Button variant="ghost" size="sm" onClick={() => { onReset(); setPopoverOpen(false) }}>Reset</Button><Button size="sm" onClick={() => { onApply(); setPopoverOpen(false) }}>Apply</Button></div></PopoverContent></Popover></div><div className="sm:hidden"><Sheet open={sheetOpen} onOpenChange={(open) => { if (open) onOpening(); setSheetOpen(open) }}><Tooltip><TooltipTrigger render={<SheetTrigger render={trigger} />}><span className="sr-only">Open filters</span></TooltipTrigger><TooltipContent>Patient filters</TooltipContent></Tooltip><SheetContent side="right"><SheetHeader><SheetTitle>Patient filters</SheetTitle><SheetDescription>Narrow the global patient directory.</SheetDescription></SheetHeader><div className="px-4"><FilterFields idPrefix="mobile-global-patient" draft={draft} setDraft={setDraft} doctors={doctors} /></div><SheetFooter><Button variant="outline" onClick={() => { onReset(); setSheetOpen(false) }}>Reset</Button><Button onClick={() => { onApply(); setSheetOpen(false) }}>Apply</Button></SheetFooter></SheetContent></Sheet></div></>
}

function LoadingState() { return <div role="status" aria-label="Loading patients" className="space-y-3"><span className="sr-only">Loading patients</span><Card className="hidden md:block"><CardContent className="space-y-4 p-5">{Array.from({ length: 5 }, (_, i) => <Skeleton key={i} className="h-8 w-full" />)}</CardContent></Card><div className="grid gap-3 md:hidden">{Array.from({ length: 3 }, (_, i) => <Skeleton key={i} className="h-52 w-full rounded-xl" />)}</div></div> }

function Actions({ patient, doctorName, deleting, onDelete }: { patient: GlobalPatient; doctorName: string; deleting: boolean; onDelete: (patient: GlobalPatient) => void }) {
  return <div className="flex justify-end gap-1"><PatientFormDialog mode="edit" patient={patient} doctorName={doctorName} trigger={<Button variant="ghost" size="icon-sm" aria-label={`Edit ${patient.name}`}><Pencil aria-hidden="true" /></Button>} /><Tooltip><TooltipTrigger render={<Button variant="ghost" size="icon-sm" aria-label={`Delete ${patient.name}`} disabled={deleting} onClick={() => onDelete(patient)} />}><Trash2 aria-hidden="true" /></TooltipTrigger><TooltipContent>Delete patient</TooltipContent></Tooltip></div>
}

function PatientResults({ patients, deletingId, onDelete }: { patients: GlobalPatient[]; deletingId: string | null; onDelete: (patient: GlobalPatient) => void }) {
  const nameFor = (patient: GlobalPatient) => patient.doctor?.name ?? "Doctor unavailable"
  return <><Card className="hidden overflow-hidden py-0 md:block"><Table><TableHeader><TableRow><TableHead className="pl-5">Patient</TableHead><TableHead>Age / gender</TableHead><TableHead>Phone</TableHead><TableHead>Condition</TableHead><TableHead>Appointment</TableHead><TableHead>Doctor</TableHead><TableHead className="w-24 pr-5"><span className="sr-only">Actions</span></TableHead></TableRow></TableHeader><TableBody>{patients.map((patient) => <TableRow key={patient.id}><TableCell className="pl-5 font-medium">{patient.name}</TableCell><TableCell>{patient.age}<Badge variant="secondary" className="ml-2 capitalize">{patient.gender}</Badge></TableCell><TableCell><a href={`tel:${patient.phone}`} className="hover:underline">{patient.phone}</a></TableCell><TableCell><Badge variant="outline" className="max-w-48 truncate">{patient.condition}</Badge></TableCell><TableCell className="whitespace-nowrap">{dateFormat.format(new Date(patient.appointmentDate))}</TableCell><TableCell className="max-w-48 truncate">{nameFor(patient)}</TableCell><TableCell className="pr-5"><Actions patient={patient} doctorName={nameFor(patient)} deleting={deletingId === patient.id} onDelete={onDelete} /></TableCell></TableRow>)}</TableBody></Table></Card><div className="grid gap-3 md:hidden">{patients.map((patient) => <Card key={patient.id}><CardHeader><div className="flex items-start justify-between gap-3"><div className="min-w-0"><CardTitle className="truncate text-base">{patient.name}</CardTitle><CardDescription className="mt-1">{patient.age} years · <span className="capitalize">{patient.gender}</span></CardDescription></div><Actions patient={patient} doctorName={nameFor(patient)} deleting={deletingId === patient.id} onDelete={onDelete} /></div></CardHeader><CardContent className="grid grid-cols-2 gap-4 text-sm"><Info label="Condition">{patient.condition}</Info><Info label="Appointment">{dateFormat.format(new Date(patient.appointmentDate))}</Info><Info label="Phone"><a href={`tel:${patient.phone}`} className="hover:underline">{patient.phone}</a></Info><Info label="Doctor">{nameFor(patient)}</Info></CardContent></Card>)}</div></>
}
function Info({ label, children }: { label: string; children: ReactNode }) { return <div className="min-w-0"><p className="text-xs text-muted-foreground">{label}</p><div className="mt-1 truncate font-medium">{children}</div></div> }

export function PatientManager() {
  const router = useRouter(), pathname = usePathname(), searchParams = useSearchParams(), serialized = searchParams.toString(), queryClient = useQueryClient()
  const urlSearch = searchParams.get("search") ?? "", condition = searchParams.get("condition") ?? "", doctorId = searchParams.get("doctorId") ?? ""
  const startDate = searchParams.get("startDate") ?? "", endDate = searchParams.get("endDate") ?? ""
  const page = positive(searchParams.get("page"), 1), limit = positive(searchParams.get("limit"), 20, PAGE_SIZES)
  const [search, setSearch] = useState(urlSearch), [dateOpen, setDateOpen] = useState(false), [dateDraft, setDateDraft] = useState<DateRange | undefined>(() => rangeFrom(startDate, endDate))
  const [filterDraft, setFilterDraft] = useState<FilterDraft>({ doctorId, condition, limit })
  const [deleteTarget, setDeleteTarget] = useState<GlobalPatient | null>(null), [deleteError, setDeleteError] = useState<string | null>(null)
  const updateUrl = useCallback((updates: Readonly<Record<string, string | null>>, resetPage = false) => { const next = new URLSearchParams(serialized); for (const [key, value] of Object.entries(updates)) { if (!value) next.delete(key); else next.set(key, value) } if (resetPage) next.delete("page"); const query = next.toString(); router.replace(query ? `${pathname}?${query}` : pathname, { scroll: false }) }, [pathname, router, serialized])
  useEffect(() => { const timer = window.setTimeout(() => { const value = search.trim(); if (value !== urlSearch) updateUrl({ search: value || null }, true) }, 350); return () => window.clearTimeout(timer) }, [search, updateUrl, urlSearch])
  const parameters = useMemo<PatientListParameters>(() => { const patientSearch = optional(urlSearch), patientCondition = optional(condition); return { page, limit, ...(patientSearch ? { search: patientSearch } : {}), ...(patientCondition ? { condition: patientCondition } : {}), ...(doctorId ? { doctorId } : {}), ...(startDate ? { startDate } : {}), ...(endDate ? { endDate } : {}) } }, [condition, doctorId, endDate, limit, page, startDate, urlSearch])
  const query = useQuery(patientListQueryOptions(parameters))
  const doctorsQuery = useQuery(doctorListQueryOptions({ page: 1, limit: 100 }))
  const deleteMutation = useMutation({ mutationFn: deletePatient, onSuccess: async (patient) => { const moveBack = query.data?.patients.length === 1 && page > 1; setDeleteTarget(null); await Promise.all([queryClient.invalidateQueries({ queryKey: patientQueryKeys.lists() }), queryClient.invalidateQueries({ queryKey: dashboardQueryKeys.all })]); if (moveBack) updateUrl({ page: String(page - 1) }, false); toast.success(`${patient.name} was deleted`) } })
  const hasFilters = Boolean(urlSearch || condition || doctorId || startDate || endDate || limit !== 20)
  const getPageHref = (nextPage: number) => { const next = new URLSearchParams(serialized); if (nextPage <= 1) next.delete("page"); else next.set("page", String(nextPage)); const value = next.toString(); return value ? `${pathname}?${value}` : pathname }
  const doctors = doctorsQuery.data?.doctors ?? []

  return <PageContainer><div className="space-y-6"><div><p className="text-sm font-medium text-neutral-500">Directory</p><h2 className="mt-1 text-2xl font-semibold tracking-[-0.025em] sm:text-3xl">Patient management</h2><p className="mt-2 text-sm leading-6 text-neutral-600">Manage appointments and patient records across every doctor.</p></div>
    <div className="flex flex-col gap-2 sm:flex-row"><div className="relative min-w-0 flex-1"><Search className="pointer-events-none absolute top-1/2 left-3 size-4 -translate-y-1/2 text-muted-foreground" aria-hidden="true" /><Input className="pl-9" value={search} onChange={(event) => setSearch(event.target.value)} aria-label="Search patients" placeholder="Search by patient name, phone, condition, or gender..." /></div><div className="flex gap-2"><Popover open={dateOpen} onOpenChange={(open) => { setDateOpen(open); if (open) setDateDraft(rangeFrom(startDate, endDate)) }}><Tooltip><TooltipTrigger render={<PopoverTrigger render={<Button variant={startDate || endDate ? "default" : "outline"} size="icon" aria-label="Appointment date filter" />} />}><CalendarDays aria-hidden="true" /></TooltipTrigger><TooltipContent>Appointment dates</TooltipContent></Tooltip><PopoverContent align="end" className="w-auto max-w-[calc(100vw-2rem)] p-0"><div className="p-4"><p className="font-medium">Appointment range</p><p className="mt-1 text-xs text-muted-foreground">{dateDraft?.from ? `${format(dateDraft.from, "MMM d, yyyy")}${dateDraft.to ? ` – ${format(dateDraft.to, "MMM d, yyyy")}` : ""}` : "Any date"}</p></div><Separator /><Calendar mode="range" selected={dateDraft} onSelect={setDateDraft} /><Separator /><div className="flex justify-end gap-2 p-3"><Button variant="ghost" size="sm" onClick={() => setDateDraft(undefined)}>Clear</Button><Button size="sm" onClick={() => { updateUrl({ startDate: iso(dateDraft?.from) || null, endDate: iso(dateDraft?.to) || null }, true); setDateOpen(false) }}>Apply</Button></div></PopoverContent></Popover><FilterControls active={Boolean(doctorId || condition || limit !== 20)} draft={filterDraft} setDraft={setFilterDraft} doctors={doctors} onOpening={() => setFilterDraft({ doctorId, condition, limit })} onReset={() => { const reset = { doctorId: "", condition: "", limit: 20 }; setFilterDraft(reset); updateUrl({ doctorId: null, condition: null, limit: null }, true) }} onApply={() => updateUrl({ doctorId: filterDraft.doctorId || null, condition: filterDraft.condition.trim() || null, limit: filterDraft.limit === 20 ? null : String(filterDraft.limit) }, true)} /></div></div>
    {hasFilters && <div className="flex flex-wrap items-center gap-2">{urlSearch && <FilterBadge label={`Search: ${urlSearch}`} onRemove={() => { setSearch(""); updateUrl({ search: null }, true) }} />}{doctorId && <FilterBadge label={`Doctor: ${doctors.find((doctor) => doctor.id === doctorId)?.name ?? "Selected"}`} onRemove={() => updateUrl({ doctorId: null }, true)} />}{condition && <FilterBadge label={`Condition: ${condition}`} onRemove={() => updateUrl({ condition: null }, true)} />}{(startDate || endDate) && <FilterBadge label={`Appointment: ${startDate || "Any"} – ${endDate || "Any"}`} onRemove={() => updateUrl({ startDate: null, endDate: null }, true)} />}{limit !== 20 && <FilterBadge label={`${limit} per page`} onRemove={() => updateUrl({ limit: null }, true)} />}<Button variant="ghost" size="sm" onClick={() => { setSearch(""); router.replace(pathname, { scroll: false }) }}>Clear all</Button></div>}
    {query.isPending ? <LoadingState /> : query.isError ? <Alert variant="destructive"><AlertTitle>Patients could not be loaded</AlertTitle><AlertDescription className="flex flex-col items-start justify-between gap-3 sm:flex-row sm:items-center"><span>{query.error instanceof PatientApiError && query.error.kind === "network" ? "Check your connection and try again." : "The server returned an unexpected response."}</span><Button variant="outline" size="sm" onClick={() => void query.refetch()}>Try again</Button></AlertDescription></Alert> : query.data.patients.length === 0 ? <Card><CardHeader className="items-center py-14 text-center"><UsersRound className="size-6 text-muted-foreground" /><CardTitle>{hasFilters ? "No matching patients" : "No patients yet"}</CardTitle><CardDescription>{hasFilters ? "Adjust or clear the current filters." : "Patients added from Doctor profiles will appear here."}</CardDescription></CardHeader></Card> : <section aria-label="Patients" className="relative space-y-5">{query.isFetching && <p role="status" className="absolute -top-8 right-0 flex items-center gap-2 text-xs text-muted-foreground"><LoaderCircle className="size-3.5 animate-spin" />Updating</p>}<PatientResults patients={query.data.patients} deletingId={deleteMutation.isPending ? deleteTarget?.id ?? null : null} onDelete={(patient) => { setDeleteError(null); setDeleteTarget(patient) }} />{query.data.pagination.totalPages > 1 && <div className="flex flex-col items-center justify-between gap-3 border-t pt-5 sm:flex-row"><p className="text-sm text-muted-foreground">Page {page} of {query.data.pagination.totalPages} · {query.data.pagination.total} patients</p><Pagination className="mx-0 w-auto"><PaginationContent><PaginationItem><PaginationPrevious href={page > 1 ? getPageHref(page - 1) : "#"} aria-disabled={page <= 1} tabIndex={page > 1 ? undefined : -1} className={cn(page <= 1 && "pointer-events-none opacity-50")} /></PaginationItem><PaginationItem><PaginationNext href={page < query.data.pagination.totalPages ? getPageHref(page + 1) : "#"} aria-disabled={page >= query.data.pagination.totalPages} tabIndex={page < query.data.pagination.totalPages ? undefined : -1} className={cn(page >= query.data.pagination.totalPages && "pointer-events-none opacity-50")} /></PaginationItem></PaginationContent></Pagination></div>}</section>}
    <AlertDialog open={deleteTarget !== null} onOpenChange={(open) => { if (!open && !deleteMutation.isPending) setDeleteTarget(null) }}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete {deleteTarget?.name}?</AlertDialogTitle><AlertDialogDescription>This permanently removes the patient record and cannot be undone.</AlertDialogDescription></AlertDialogHeader>{deleteError && <Alert variant="destructive"><AlertDescription>{deleteError}</AlertDescription></Alert>}<AlertDialogFooter><AlertDialogCancel disabled={deleteMutation.isPending}>Cancel</AlertDialogCancel><AlertDialogAction variant="destructive" disabled={deleteMutation.isPending} onClick={async () => { if (!deleteTarget || deleteMutation.isPending) return; try { await deleteMutation.mutateAsync(deleteTarget.id) } catch (error: unknown) { setDeleteError(error instanceof PatientApiError && error.kind === "network" ? "Unable to reach the server. Try again." : "The patient could not be deleted. It may already have been removed.") } }}>{deleteMutation.isPending && <LoaderCircle className="animate-spin" />}{deleteMutation.isPending ? "Deleting…" : "Delete patient"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div></PageContainer>
}

function FilterBadge({ label, onRemove }: { label: string; onRemove: () => void }) { return <Badge variant="outline" className="max-w-full"> <span className="truncate">{label}</span><button type="button" onClick={onRemove} aria-label={`Remove ${label}`} className="ml-1 rounded-sm focus-visible:outline-none focus-visible:ring-2"><X className="size-3" aria-hidden="true" /></button></Badge> }
